name: pytest
on: [ pull_request ]
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: bigger-yoshi
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          cd api
          touch .env
          echo SECRET_KEY='${{ secrets.BACKEND_AUTH_KEY }}' >> .env
          pytest
