name: CI Checks
on: [ pull_request ]
jobs:
  pre-commit-linter:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job shouldn't fail unless you don't have pre-commit configured locally :/"
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: >
          pip install pre-commit &&
          pre-commit run --all-files
