name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job shouldn't fail unless you don't have pre-commit configured locally :/"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: actions/checkout@v3
      - run: >
          pip install -r pre-commit
          pre-commit run --all-files
